BaseUrl= "https://www.djtennessee.com/"
LanguageCode= "en-US"
Title= "Minecraft Creations"
paginate = 20
DisqusShortname = ""
Copyright = "All rights reserved - "
canonifyURLs = true
relativeURLs = false
metaDataFormat = "yaml"
theme = "air"

[permalinks]
  post = "/blog/:slug/"

[author]
  name = "DJTennessee"
  email = ""

[params]
  description = "by DJTennessee"
  cover = "/"
  author = "DJTennessee"
  authorlocation = ""
  authorwebsite = ""
  bio= "I love making fun, new creations in Minecraft!"
  logo = "images/djhead.png"
  #https://crafatar.com/avatars/8beb94179a864463a0f34d3e46273a6c.png
  googleAnalyticsUserID = ""
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  RSSLink = ""
  githubName = ""
  twitterName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false

[taxonomies]
  tag = "tags"
  book = "books"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 15
 
[[menu.main]]
  name = "About Me"
  url = "/about/"
  weight = 10

[[menu.main]]
  name = "Books"
  url = "/books/"
  weight = 5

[[menu.main]]
  name = "RSS Feed"
  url = "/index.xml"
  weight = 0